if_snp: True
if_structure: True
if_RNA_snp_split: True
if_cuttag: False

ref_genome: GRCm38 # GRCm38 or GRCh37d5
yperx_threshold: 0.12
softwares:
  HIRES: /share/home/zliu/biosoft/hires-utils/
  HICKIT: /share/home/zliu/biosoft/hickit-0.1.1_x64-linux/
  HICKIT_PAIRS_TO_CON: /share/home/zliu/biosoft/dip-c/scripts/hickit_pairs_to_con.sh
  HICKIT_IMPUTE_PAIRS_TO_CON: /share/home/zliu/biosoft/dip-c/scripts/hickit_impute_pairs_to_con.sh
  DIP_C: /share/home/zliu/biosoft/dip-c/dip-c
  HICKIT_3DG_TO_3DG_RESCALE_UNIT: /share/home/zliu/biosoft/dip-c/scripts/hickit_3dg_to_3dg_rescale_unit.sh
refs:
  GRCm38:
    bwa_mem2_index: /share/Data/public/ref_genome/mouse_ref/M23/bwamem2/genome.fa
    star_index: /share/home/zliu/share/Data/public/ref_genome/mouse_ref/M23/RNA_snp_split/CAST_B6_star_index
    annotations: /share/Data/public/ref_genome/mouse_ref/M23/raw_data/annotation.gtf
    snp: /share/home/zliu/share/Data/public/ref_genome/GRCm38/snp/Tan.CAST_B6.snp.GRCm38.withchr.txt
    par: /share/home/zliu/share/Data/public/ref_genome/GRCm38/raw_data/par.bed
    RNAsnp: /share/home/zliu/share/Data/public/ref_genome/mouse_ref/M23/RNA_snp_split/all_SNPs_CAST_EiJ_GRCm38.txt.gz

  GRCh37d5:
    bwa_mem2_index: /share/Data/public/ref_genome/GRCh37d5/bwa_mem2_index/genome.fa
    #star_index: /share/Data/public/ref_genome/GRCh37/star_index
    star_index: /share/Data/public/ref_genome/human_ref/GRCh37d5/RNA_snp_split/NA12878_star_index #for NA12878
    annotations: /share/Data/public/ref_genome/GRCh37/raw_data/gencode.v19.annotation.gtf
    snp: /share/home/zliu/share/Data/public/ref_genome/GRCh37/snp_file/GM12878/NA12878.withchr.txt
    par: /share/home/zliu/share/Data/public/ref_genome/GRCh37/raw_data/par.withchr.bed
    RNAsnp: /share/Data/public/ref_genome/human_ref/GRCh37d5/RNA_snp_split/NA12878.withchr.SNPsplit.txt.gz
resources:
  cutadapt_cpu_threads: 10
  bwa_cpu_threads: 10
  hires_clean_cpu_threads: 10 
  star_cpu_threads: 20
  align2pairs_cpu_threads: 10
  count_cpu_threads: 6
  generateStat_cpu_threads: 40
